#Домашнє завдання до тем apply(), groupby(), pivot_table()

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('/content/data/supermarket_sales.csv')

In [5]:
df.head(6)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
5,699-14-3026,C,Naypyitaw,Normal,Male,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,18:30,Ewallet,597.73,4.761905,29.8865,4.1

1. Дослідимо, який філіал супермаркету ('Branch') є найприбутковішим. Для цього знайдіть сумарний прибуток за кожним філіалом і виявіть, який філіал має найвищий.

In [3]:
branch_profit=df.groupby('Branch')['gross income'].sum()
print('Сумарний прибуток за філіалами:')
print(branch_profit)

Сумарний прибуток за філіалами:
Branch
A    5057.1605
B    5057.0320
C    5265.1765
Name: gross income, dtype: float64

In [6]:
best_branch=branch_profit.idxmax()
print(f'\nНайприбутковіший філіал:{best_branch}(прибуток:{branch_profit.max():2f})')

Найприбутковіший філіал:C(прибуток:5265.176500)

2. В якому місті знайходиться філіал з найвищим прибутком? Може в тому місці нам розмітисти ще один магазин.  
Знайдіть відповідь за допомогою функціоналу Pandas.

In [9]:
city_profit=df.groupby('City')['gross income'].sum()
print('Сумарний прибуток за містами:')
print(city_profit)

Сумарний прибуток за містами:
City
Mandalay     5057.0320
Naypyitaw    5265.1765
Yangon       5057.1605
Name: gross income, dtype: float64

In [10]:
best_city=city_profit.idxmax()
print(f'\nМісто з найвищим прибутком: {best_city}')

Місто з найвищим прибутком: Naypyitaw

3.1. Створіть зводну таблицю, яка покаже, скільки покупок (інвойсів) було зроблено в кожній з філій (`Branch`) за різними категоріями товарів. Запишіть таблицю в змінну `invoices_by_category` і виведіть змінну на екран.
Ця таблиця допоможе проаналізувати, в якій філії купують найбільше товарів кожної з категорій.

In [11]:
invoices_by_category=df.pivot_table(
    index='Branch',
    columns='Product line',
    values='Invoice ID',
    aggfunc='count'
)

invoices_by_category

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,60,51,58,47,65,59
B,55,62,50,53,50,62
C,55,65,66,52,45,45

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1rueAdko6S3UxIHGtojetTxlES-EyM6Yb)

3.2. Викристовуючи змінну `invoices_by_category` дайте відповідь програмно (тобто значення треба не просто знайти очима, а вивести за допомогою коду), в якому філіалі магазину (`Branch`) найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" (`Electronic accessories`)?

In [13]:
best_branch_elec=invoices_by_category['Electronic accessories'].idxmax()
max_invoices=invoices_by_category['Electronic accessories'].max()

print(f"Філіал з найбільшою кількістю інвойсів категорії Electronic accessories: {best_branch_elec} ({max_invoices} інвойсів)")

Філіал з найбільшою кількістю інвойсів категорії Electronic accessories: A (60 інвойсів)

4-6. **Творче завдання на розвиток аналітичного мислення**

Крок 1. Сформулюйте ТРИ питання (гіпотези) до наявних даних, які допомогли б вам зрозуміти, які користувачі що, де та коли найбільше/найменше купують, аби дати на основі цих гіпотез рекомендації бізнесу. Звісно питання мають бути не тими, на які ми вже відповіли в завданнях модулю.

Крок 2. Знайдіть відповіді на свої питання з допомогою функціоналу pandas.

Крок 3. Напишіть, як відповідь на це питання може бути використана для прийняття бізнес рішень.   
   
 Питання можуть бути будь-якої складності, але їх має бути 3. Кожне питання оцінюється як 1 завдання. Без виконання цього завдання ДЗ не приймається. Якщо є питання щодо виконання - пишіть у чат 🙌

In [14]:
#Гіпотеза 1. В який час доби клієнти роблять найбільше покупок?
df['Hour']=pd.to_datetime(df['Time']).dt.hour
hourly_sales=df.groupby('Hour')['Invoice ID'].count()
best_hour=hourly_sales.idxmax()
print(f"Пікова година покупок: {best_hour}:00")

Пікова година покупок: 19:00

/tmp/ipykernel_1724/1625874120.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Hour']=pd.to_datetime(df['Time']).dt.hour

Бізнес рішення: Оптимізуваи графік зміни касирів та викладку товару в пікові години, а також планувати технічні перерви у години найнижчої активності

In [15]:
#Гіпотеза 2: Чи відрізняється середній чек та вибір способу оплати (Cash, Credit card, Ewallet) залежно від типу клієнта(Member vs Normal)?
payment_by_customer=df.pivot_table(index='Customer type', columns='Payment', values='Total',aggfunc='mean')
print(payment_by_customer)

Payment              Cash  Credit card     Ewallet
Customer type
Member         325.363187   335.880654  321.682957
Normal         326.963378   309.320860  316.316038

Бізнес-рішення: Якщо лояльні клієнти частіше користуються електонними гаманцями або витрачають більше, можна впровадити спеціальні бонуси та кешбек за цей спосіб оплати для стимулювання повторних покупок.

In [16]:
# Гіпотеза 3: Яка категорія товарів приносить найвищий середній рейтинг задоволеності клієнтів ?
rating_by_category=df.groupby('Product line') ['Rating'].mean().sort_values(ascending=False)
print(rating_by_category)

Product line
Food and beverages        7.113218
Fashion accessories       7.029213
Health and beauty         7.003289
Electronic accessories    6.924706
Sports and travel         6.916265
Home and lifestyle        6.837500
Name: Rating, dtype: float64

Бізнес-рішення:Категорії з найнижчим середнім рейтингом потребують перевірки якості товарів або асортименту, а категорії з високим рейтингом можна активніше рекламувати як флагманські.